# Generated by Django 3.0.4 on 2020-03-14 12:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='FB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
